### ISSUE TITLE
Open spec up to other templates - don't confine to "default"

### ISSUE THREAD

**Issue by gregturn** [mamund/hal-forms#24]
```
key - The unique identifier for this template object. This is a REQUIRED element. For this release, the only valid value for key is "default". If this element is missing, set to empty or is unparsable, this template object SHOULD be ignored.
```

Right now, the spec says that the ONLY template allowed is the default one. Can we revise the spec to read that "default" is the, so far, the only pre-defined one? This would support the ability to have multiple templates.

**Comment by mamund** [comment]
Yep. Good idea. This will clear up confusion in the docs. I'll make a good this week and pay for review.

**Comment by JorgeFerrer** [comment]
Hey Greg, Mike,

The main problem I see with allowing additional templates other than "default" is, what is the meaning of "default" then? 

When there is only "default" and the whole document represents one relation type then it's clear. This is the case in all the examples from the [HAL-FORMS Media Type specification](https://rwcbook.github.io/hal-forms/).

However in the example of the [Spring blog entry](https://spring.io/blog/2018/01/12/building-richer-hypermedia-with-spring-hateoas), since _templates is included in the HAL response of an employee resource, then the context is lost. It seems it has been assumed that "default" means an update operation on the resource where _templates is included. If this is correct, then the HAL-FORMS spec should clearly explain the meaning of "default" in this context.

Makes sense?

**Comment by JorgeFerrer** [comment]
To help understand my previous question, I've prepared some alternative ways to provide the representation of the Employee resource from Spring's blog entry. I'm keeping the original from the blog as Option 1. Our understanding of the HAL-FORMS spec wast that it wasn't correct to add _templates in the HAL response for the employee. I'm providing as Option 2 and Option 3, what we interpreted to be correct.

**Option 1: HAL document containing HAL-FORMS**

This is the option that is provided as an example in the Blog Post [Building richer hypermedia with Spring HATEOAS](https://spring.io/blog/2018/01/12/building-richer-hypermedia-with-spring-hateoas).

The problem I see with this example is that it's not clearly defined what the template named "default" really means. Here it seems to be an update operation for the "self" resource. But that's a convention that is out of the scope of HAL or HAL-FORMS isn't it?

```json
{
  "id" : 1,
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "role" : "ring bearer",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/employees/1"
    },
    "employees" : {
      "href" : "http://localhost:8080/employees"
    }
  },
  "_templates" : {
    "default" : {
      "title" : null,
      "method" : "put",
      "contentType" : "",
      "properties" : [ {
        "name" : "firstName",
        "required" : true
      }, {
        "name" : "id",
        "required" : true
      }, {
        "name" : "lastName",
        "required" : true
      }, {
        "name" : "role",
        "required" : true
      } ]
    },
    "deleteEmployee" : {
      "title" : null,
      "method" : "delete",
      "contentType" : "",
      "properties" : [ ]
    }
  }
}
```

**Option 2: HAL document links to separate HAL-FORMS resource**

This is an alternative implementation of the example provided in the Spring blog. In this case the affordances are both provided as regular _links, where the rel key can be dereferenced to obtain the HAL-FORMS resource associated to that operation.

*HAL Resource*

```json
{
  "id" : 1,
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "role" : "ring bearer",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/employees/1"
    },
    "employees" : {
      "href" : "http://localhost:8080/employees"
    },
    "http://localhost:8080/rels/update": {
      "href" : "http://localhost:8080/employees",
      "type" : "application/prs.hal-forms+json"
    }
    "http://localhost:8080/rels/deleteEmployee" : {
      "href" : "http://localhost:8080/employees/1",
      "type" : "application/prs.hal-forms+json"
    }
  },
}
```

Note how in this case I've provided the HAL-FORMS Mime type in the Link Object. That's not mandatory, but can be helpful for the client.

*HAL-FORMS Resource for Create*

```json
{
   "_links" : {
     "self" : {
       "href" : "http://api.example.org/rels/update"
     }
   },
   "_templates" : {
    "default" : {
      "title" : null,
      "method" : "put",
      "contentType" : "",
      "properties" : [ {
        "name" : "firstName",
        "required" : true
      }, {
        "name" : "id",
        "required" : true
      }, {
        "name" : "lastName",
        "required" : true
      }, {
        "name" : "role",
        "required" : true
      } ]
    },
  }
}
```

*HAL FORMS Resource for Delete*

```json
{
   "_links" : {
     "self" : {
       "href" : "http://api.example.org/rels/deleteEmployee"
     }
   },
  "_templates" : {
    "default" : {
      "title" : null,
      "method" : "delete",
      "contentType" : "",
      "properties" : [ ]
    }
  }
}
```
**Option 3: Same as 2 but form resources are embedded**

This option is still a pure HAL resource, with no extensions. It embeds resources of type HAL-FORM.

HAL Resource

```json
{
  "id" : 1,
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "role" : "ring bearer",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/employees/1"
    },
    "employees" : {
      "href" : "http://localhost:8080/employees"
    },
    "http://localhost:8080/rels/update" : {
      "href" : "http://localhost:8080/employees"
    }
  },
  "_embedded": {
    "http://localhost:8080/rels/update": {
	   "_links" : {
	     "self" : {
	       "href" : "http://api.example.org/rels/update"
	     }
	   },
	   "_templates" : {
	    "default" : {
	      "title" : null,
	      "method" : "put",
	      "contentType" : "",
	      "properties" : [ {
	        "name" : "firstName",
	        "required" : true
	      }, {
	        "name" : "id",
	        "required" : true
	      }, {
	        "name" : "lastName",
	        "required" : true
	      }, {
	        "name" : "role",
	        "required" : true
	      } ]
	    },
	  }
    },
    "http://localhost:8080/rels/deleteEmployee": {
      "_links" : {
        "self" : {
          "href" : "http://api.example.org/rels/deleteEmployee"
        }
      },
    "_templates" : {
      "default" : {
        "title" : null,
        "method" : "delete",
        "contentType" : "",
        "properties" : [ ]
      }
    }
  }
}
```

**Comment by JorgeFerrer** [comment]
Hey Greg, 

Thanks for the detailed answer. First of all I wanted to apologize if my previous comment has come out as criticism. It was not my intention. We are developing RESTful APIs in several projects now and Spring Boot (and thus Spring REST) is one of the technologies we are using, so we are very excited with the amazing improvements you guys are making to make it easier.

The reason for my comments is because our interpretation of HAL-FORMS had been different from what you propose in the blog example. What we were doing looked more like options 2 and 3 in my previous comment.

We are just trying to find out from Mike if both approaches are valid and if so what are the pros and cons of each.

> "default" comes across as either the most important action provided in the document, or at least the most likely one to be used. In this example, I would clearly favor PUT over DELETE. For an aggregate resource, I would put POST.

The problem I see with this definition of "default" as the most important action is that it varies per resource. So that takes us back to documenting the meaning for each resource, instead of being able to just define the types of relations (or actions) independently of where they are used (which is what we understand Mike advocates). 

Makes sense?

**Comment by gregturn** [comment]
> First of all I wanted to apologize if my previous comment has come out as criticism. 

None taken!

I enjoy finding someone else trying to implement RESTful concepts (especially if they are using our stuff) and being to hammer out gaps in a spec quite exciting. That was we can build stronger APIs.

👍

**Comment by JorgeFerrer** [comment]
Thanks Greg!

@mamund if you have any input or recommendations on the examples above they would be very appreciated.

**Comment by mamund** [comment]
yes, hello @gregturn and @JorgeFerrer 

1) at this stage, whatever change we make needs to be backward compatible. 
2) first stage is to define behavior that _allows_ extending the collection
3) an additional effort would be to define details of an extension on how to define/use extended values in the collection.

we can accomplish #1 and #2 with just small changes in the wording of the doc. 

doing #3 will take more time/agreement/effort.

let's start w/ #2.  i'm open to language.

**Comment by gregturn** [comment]
Regarding (2):

Replace (section in _templates):

> The unique identifier for this template object. This is a REQUIRED element. For this release, the only valid value for key is "default". If this element is missing, set to empty or is unparsable, this template object SHOULD be ignored.

with...

> The unique identifier for this template object. This is a REQUIRED element. For this release, the only pre-defined value for key is "default". If this element is missing, set to empty or is unparsable, this template object SHOULD be ignored. If the key is something other, clients may choose to ignore the template entry.

That would let existing clients that assume only the existence of "default" to continue with the option to ignore any other templates, presuming they flat out ignore any other templates. However, clients can also proceed to accept ALL templates.

This wording DOES imply that a HAL-FORMS document could contain multiple links, with none of them being "default".

wdyt?

**Comment by mamund** [comment]
i think we'll need to keep default (in order to be backward-compatible to any existing implementations)

"if there is only one element in the collection is MUST be "default"

wdyt?

**Comment by ahdezma** [comment]
Hi all, I'm very interested in this issue and I've been following it from the beginning but I still have some doubts.

In the spec, it is said that:

> The **HAL-FORMS** media type design follows many of the **HAL** media type conventions. For this reason, **HAL-FORMS** "looks like **HAL**." However, it is important to keep in mind that **HAL-FORMS** is not the same as **HAL** — the two should not be thought of as interchangeable in any way.

Also, at the last part, where a _"Process Flow for HAL-FORMS Documents"_ is suggested, it says that: _first servers should emit **HAL** responses with links to the **HAL-FORMS** documents. And then, **HAL** clients should parse the **HAL** response and request the **HAL-FORMS** documents._

Is not this the suggested workflow anymore?

That's my first doubt. 

Second (and last), taking a look to the _"The `_templates` Element"_ section it is said that:

> The `_templates` element describes the available state transition details including the HTTP method, message content-type, and arguments for the transition

What I get from this sentence (and also from the whole spec) is that the `_templates` will serve the purpose of serving different "forms" for the same action (in the spec examples we can find **HAL-FORMS** documents for a `filter` and a `create` request, both of them in separate **HAL-FORMS** and, therefore, with their own `_templates` object, but never both of them inside the same `_templates`). However what I get from reading this issue (and looking at the examples from the [SpringBoot blog post](https://spring.io/blog/2018/01/12/building-richer-hypermedia-with-spring-hateoas)) is that the `_templates` object could be also used to provide information about two (or more) totally different operations (update and delete in the example).

So... which of the two uses for `_templates` is correct?

Thank you all :)

**Comment by mamund** [comment]
the spec is designed to support HAL-FORMS as a separate document. however, the HAL-FORMS spec is not going to be written to _prevent_ people from doing other things w/ HAL-FORMS.

IOW, the spec will focus on the proper use and not on the improper use.

does this help?

**Comment by ahdezma** [comment]
Ok, yeah, makes sense. Thanks, @mamund!

**Comment by mamund** [comment]
@JorgeFerrer 

> i think we'll need to keep default (in order to be backward-compatible to any existing implementations)
>
> "if there is only one element in the collection the key MUST/SHOULD be set to "default"

wdyt?

**Comment by JorgeFerrer** [comment]
@mamund Yeah, I think that's a very good way to keep backwards compatibility while still leaving the door open to not having to include "default" as one of the _template keys when there are several.

And I think the sentence should be with MUST, not with SHOULD: "if there is only one element in the collection the key MUST be set to "default"

@gregturn I think that with this change it would be more clear if you guys used a more meaningful _template key like "update" or "updateEmployee" instead of the "default"

**Comment by mamund** [comment]
I'm ok with MUST here. Anyone object?

**Comment by gregturn** [comment]
MUST is perfect. Sounds like we have consensus.

**Comment by mamund** [comment]
Ok. I'll write up a branch and pay for final review.

**Comment by mamund** [comment]
OK, as I was working on the PR it finally dawned on me that the edition of HAL-FORMS here in my repo (mamund/hal-forms) has not been kept sync'd w. the edition released for the book (rwcbook/hal-forms). 

sigh...

so, I will do a bit of clean up to sync them back up. AFAICT, it's all non-breaking but i want to get them sorted out.

so that leaves a single element which is potentially a breaking change. @gregturn pointed this out in #25 and i just missed it.  mamund/hal-forms claims +self+ as the collection key, rwcbook/hal-forms claims +default+ as they collection key. while we _can_ allow both, it gets messy:

> If there is only one item in the collection the item's +key+ value MUST be set to "self" or "default." However, in cases where there is more than one item in the collection (e.g. two), the collection MUST NOT contain both a key with the value set to "self" and another key with the value set to "default."

that's just a mess!

I think we should revert to +self+ as in the mamund/hal-forms spec.  but this has the potential to break things. -- maybe break more ppl than using +default+.

any thoughts?

**Comment by mamund** [comment]
@gregturn @JorgeFerrer and others...

i created the PR for review. turns out it's a bit messy since i haven't been grooming the sync'd repos well, but hopefully this won't get in the way of this issue.

i'll let this rest a day or so to give us a chance to review/comment before i resolve the merge.

cheers.

**Comment by gregturn** [comment]
BUMP

**Comment by mamund** [comment]
after the dust settles on the `contentType` changes, we can revisit this and close it out next.

thanks for your help on making HAL-FORMS better.
